<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class LeadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $leads = [
            [
                'nomor' => 'UF25020019',
                'tanggal' => '2025-02-21',
                'nama' => 'Customer 25',
                'nohp' => '82313323221',
                'alamat' => 'Jalan Raya 1',
                'kelurahan' => 'KELURAHAN 25',
                'kecamatan' => 'KECAMATAN 20',
                'kota' => 'KOTA 3',
                'tipe' => 'Mobil 9',
                'warna' => 'MERAH',
                'hargajual' => 417482811,
                'discount' => 52400000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020032',
                'tanggal' => '2025-02-28',
                'nama' => 'Customer 33',
                'nohp' => '82313323222',
                'alamat' => 'Jalan Raya 2',
                'kelurahan' => 'KELURAHAN 33',
                'kecamatan' => 'KECAMATAN 26',
                'kota' => 'KOTA 7',
                'tipe' => 'Mobil 11',
                'warna' => 'MERAH',
                'hargajual' => 258845594,
                'discount' => 16396396,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020023',
                'tanggal' => '2025-02-24',
                'nama' => 'Customer 30',
                'nohp' => '82313323223',
                'alamat' => 'Jalan Raya 3',
                'kelurahan' => 'KELURAHAN 30',
                'kecamatan' => 'KECAMATAN 24',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 12',
                'warna' => 'MERAH',
                'hargajual' => 278250233,
                'discount' => 15000000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020026',
                'tanggal' => '2025-02-27',
                'nama' => 'Customer 10',
                'nohp' => '82313323224',
                'alamat' => 'Jalan Raya 4',
                'kelurahan' => 'KELURAHAN 10',
                'kecamatan' => 'KECAMATAN 9',
                'kota' => 'KOTA 7',
                'tipe' => 'Mobil 12',
                'warna' => 'MERAH',
                'hargajual' => 278250233,
                'discount' => 15000000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020034',
                'tanggal' => '2025-02-28',
                'nama' => 'Customer 29',
                'nohp' => '82313323225',
                'alamat' => 'Jalan Raya 5',
                'kelurahan' => 'KELURAHAN 29',
                'kecamatan' => 'KECAMATAN 23',
                'kota' => 'KOTA 5',
                'tipe' => 'Mobil 1',
                'warna' => 'HITAM',
                'hargajual' => 177482576,
                'discount' => 10000000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020010',
                'tanggal' => '2025-02-15',
                'nama' => 'Customer 13',
                'nohp' => '82313323226',
                'alamat' => 'Jalan Raya 6',
                'kelurahan' => 'KELURAHAN 13',
                'kecamatan' => 'KECAMATAN 11',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 1',
                'warna' => 'HITAM',
                'hargajual' => 177482576,
                'discount' => 10000000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020017',
                'tanggal' => '2025-02-19',
                'nama' => 'Customer 1',
                'nohp' => '82313323227',
                'alamat' => 'Jalan Raya 7',
                'kelurahan' => 'KELURAHAN 1',
                'kecamatan' => 'KECAMATAN 1',
                'kota' => 'KOTA 8',
                'tipe' => 'Mobil 1',
                'warna' => 'HITAM',
                'hargajual' => 177482576,
                'discount' => 10000000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020025',
                'tanggal' => '2025-02-27',
                'nama' => 'Customer 5',
                'nohp' => '82313323228',
                'alamat' => 'Jalan Raya 8',
                'kelurahan' => 'KELURAHAN 5',
                'kecamatan' => 'KECAMATAN 5',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 3',
                'warna' => 'HITAM',
                'hargajual' => 151371878,
                'discount' => 10000000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020011',
                'tanggal' => '2025-02-15',
                'nama' => 'Customer 3',
                'nohp' => '82313323229',
                'alamat' => 'Jalan Raya 9',
                'kelurahan' => 'KELURAHAN 3',
                'kecamatan' => 'KECAMATAN 3',
                'kota' => 'KOTA 2',
                'tipe' => 'Mobil 4',
                'warna' => 'HITAM',
                'hargajual' => 162139094,
                'discount' => 10000000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020007',
                'tanggal' => '2025-02-13',
                'nama' => 'Customer 27',
                'nohp' => '82313323230',
                'alamat' => 'Jalan Raya 10',
                'kelurahan' => 'KELURAHAN 27',
                'kecamatan' => 'KECAMATAN 22',
                'kota' => 'KOTA 3',
                'tipe' => 'Mobil 4',
                'warna' => 'HITAM',
                'hargajual' => 163352944,
                'discount' => 10000000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020016',
                'tanggal' => '2025-02-19',
                'nama' => 'Customer 12',
                'nohp' => '82313323231',
                'alamat' => 'Jalan Raya 11',
                'kelurahan' => 'KELURAHAN 12',
                'kecamatan' => 'KECAMATAN 11',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 5',
                'warna' => 'HITAM',
                'hargajual' => 267521361,
                'discount' => 59300000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020003',
                'tanggal' => '2025-02-10',
                'nama' => 'Customer 32',
                'nohp' => '82313323232',
                'alamat' => 'Jalan Raya 12',
                'kelurahan' => 'KELURAHAN 32',
                'kecamatan' => 'KECAMATAN 25',
                'kota' => 'KOTA 3',
                'tipe' => 'Mobil 9',
                'warna' => 'HITAM',
                'hargajual' => 333063548,
                'discount' => 40180181,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020006',
                'tanggal' => '2025-02-13',
                'nama' => 'Customer 23',
                'nohp' => '82313323233',
                'alamat' => 'Jalan Raya 13',
                'kelurahan' => 'KELURAHAN 23',
                'kecamatan' => 'KECAMATAN 18',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 9',
                'warna' => 'HITAM',
                'hargajual' => 323484000,
                'discount' => 45180181,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020015',
                'tanggal' => '2025-02-19',
                'nama' => 'Customer 31',
                'nohp' => '82313323234',
                'alamat' => 'Jalan Raya 14',
                'kelurahan' => 'KELURAHAN 31',
                'kecamatan' => 'KECAMATAN 24',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 9',
                'warna' => 'HITAM',
                'hargajual' => 417742789,
                'discount' => 52400000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020021',
                'tanggal' => '2025-02-22',
                'nama' => 'Customer 16',
                'nohp' => '82313323235',
                'alamat' => 'Jalan Raya 15',
                'kelurahan' => 'KELURAHAN 16',
                'kecamatan' => 'KECAMATAN 12',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 2',
                'warna' => 'KUNING',
                'hargajual' => 221558469,
                'discount' => 10000000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020014',
                'tanggal' => '2025-02-18',
                'nama' => 'Customer 6',
                'nohp' => '82313323236',
                'alamat' => 'Jalan Raya 16',
                'kelurahan' => 'KELURAHAN 6',
                'kecamatan' => 'KECAMATAN 6',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 1',
                'warna' => 'ABU - ABU',
                'hargajual' => 177482576,
                'discount' => 10000000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020033',
                'tanggal' => '2025-02-28',
                'nama' => 'Customer 14',
                'nohp' => '82313323237',
                'alamat' => 'Jalan Raya 17',
                'kelurahan' => 'KELURAHAN 14',
                'kecamatan' => 'KECAMATAN 11',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 1',
                'warna' => 'ABU - ABU',
                'hargajual' => 177482576,
                'discount' => 10000000,
                'status' => 'Tunai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020024',
                'tanggal' => '2025-02-26',
                'nama' => 'Customer 26',
                'nohp' => '82313323238',
                'alamat' => 'Jalan Raya 18',
                'kelurahan' => 'KELURAHAN 26',
                'kecamatan' => 'KECAMATAN 21',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 1',
                'warna' => 'ABU - ABU',
                'hargajual' => 177214719,
                'discount' => 10300000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020004',
                'tanggal' => '2025-02-11',
                'nama' => 'Customer 11',
                'nohp' => '82313323239',
                'alamat' => 'Jalan Raya 19',
                'kelurahan' => 'KELURAHAN 11',
                'kecamatan' => 'KECAMATAN 10',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 2',
                'warna' => 'ABU - ABU',
                'hargajual' => 206280590,
                'discount' => 27000000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020013',
                'tanggal' => '2025-02-17',
                'nama' => 'Customer 20',
                'nohp' => '82313323240',
                'alamat' => 'Jalan Raya 20',
                'kelurahan' => 'KELURAHAN 20',
                'kecamatan' => 'KECAMATAN 16',
                'kota' => 'KOTA 3',
                'tipe' => 'Mobil 8',
                'warna' => 'ABU - ABU',
                'hargajual' => 223119697,
                'discount' => 61600000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020029',
                'tanggal' => '2025-02-27',
                'nama' => 'Customer 4',
                'nohp' => '82313323241',
                'alamat' => 'Jalan Raya 21',
                'kelurahan' => 'KELURAHAN 4',
                'kecamatan' => 'KECAMATAN 4',
                'kota' => 'KOTA 1',
                'tipe' => 'Mobil 10',
                'warna' => 'ABU - ABU',
                'hargajual' => 236602026,
                'discount' => 25741041,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020005',
                'tanggal' => '2025-02-12',
                'nama' => 'Customer 9',
                'nohp' => '82313323242',
                'alamat' => 'Jalan Raya 22',
                'kelurahan' => 'KELURAHAN 9',
                'kecamatan' => 'KECAMATAN 8',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 9',
                'warna' => 'PUTIH',
                'hargajual' => 327948286,
                'discount' => 40180181,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020008',
                'tanggal' => '2025-02-13',
                'nama' => 'Customer 28',
                'nohp' => '82313323243',
                'alamat' => 'Jalan Raya 23',
                'kelurahan' => 'KELURAHAN 28',
                'kecamatan' => 'KECAMATAN 22',
                'kota' => 'KOTA 3',
                'tipe' => 'Mobil 9',
                'warna' => 'PUTIH',
                'hargajual' => 417482811,
                'discount' => 45000000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020002',
                'tanggal' => '2025-02-07',
                'nama' => 'Customer 21',
                'nohp' => '82313323244',
                'alamat' => 'Jalan Raya 24',
                'kelurahan' => 'KELURAHAN 21',
                'kecamatan' => 'KECAMATAN 17',
                'kota' => 'KOTA 2',
                'tipe' => 'Mobil 6',
                'warna' => 'PUTIH',
                'hargajual' => 254029006,
                'discount' => 52684685,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020031',
                'tanggal' => '2025-02-28',
                'nama' => 'Customer 22',
                'nohp' => '82313323245',
                'alamat' => 'Jalan Raya 25',
                'kelurahan' => 'KELURAHAN 22',
                'kecamatan' => 'KECAMATAN 17',
                'kota' => 'KOTA 2',
                'tipe' => 'Mobil 4',
                'warna' => 'MERAH CERAH',
                'hargajual' => 162139094,
                'discount' => 10000000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020020',
                'tanggal' => '2025-02-22',
                'nama' => 'Customer 7',
                'nohp' => '82313323246',
                'alamat' => 'Jalan Raya 26',
                'kelurahan' => 'KELURAHAN 7',
                'kecamatan' => 'KECAMATAN 6',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 7',
                'warna' => 'MERAH CERAH',
                'hargajual' => 270891383,
                'discount' => 65000000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020001',
                'tanggal' => '2025-02-04',
                'nama' => 'Customer 19',
                'nohp' => '82313323247',
                'alamat' => 'Jalan Raya 27',
                'kelurahan' => 'KELURAHAN 19',
                'kecamatan' => 'KECAMATAN 15',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 9',
                'warna' => 'COKLAT PASIR',
                'hargajual' => 317522075,
                'discount' => 32000000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020009',
                'tanggal' => '2025-02-14',
                'nama' => 'Customer 18',
                'nohp' => '82313323248',
                'alamat' => 'Jalan Raya 28',
                'kelurahan' => 'KELURAHAN 18',
                'kecamatan' => 'KECAMATAN 14',
                'kota' => 'KOTA 3',
                'tipe' => 'Mobil 9',
                'warna' => 'COKLAT PASIR',
                'hargajual' => 325367281,
                'discount' => 48800000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020028',
                'tanggal' => '2025-02-27',
                'nama' => 'Customer 8',
                'nohp' => '82313323249',
                'alamat' => 'Jalan Raya 29',
                'kelurahan' => 'KELURAHAN 8',
                'kecamatan' => 'KECAMATAN 7',
                'kota' => 'KOTA 4',
                'tipe' => 'Mobil 9',
                'warna' => 'COKLAT PASIR',
                'hargajual' => 322723422,
                'discount' => 51750000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020012',
                'tanggal' => '2025-02-17',
                'nama' => 'Customer 15',
                'nohp' => '82313323250',
                'alamat' => 'Jalan Raya 30',
                'kelurahan' => 'KELURAHAN 15',
                'kecamatan' => 'KECAMATAN 11',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 9',
                'warna' => 'COKLAT PASIR',
                'hargajual' => 417742789,
                'discount' => 52400000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020022',
                'tanggal' => '2025-02-24',
                'nama' => 'Customer 24',
                'nohp' => '82313323251',
                'alamat' => 'Jalan Raya 31',
                'kelurahan' => 'KELURAHAN 24',
                'kecamatan' => 'KECAMATAN 19',
                'kota' => 'KOTA 3',
                'tipe' => 'Mobil 1',
                'warna' => 'PUTIH',
                'hargajual' => 177482576,
                'discount' => 10000000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020027',
                'tanggal' => '2025-02-27',
                'nama' => 'Customer 2',
                'nohp' => '82313323252',
                'alamat' => 'Jalan Raya 32',
                'kelurahan' => 'KELURAHAN 2',
                'kecamatan' => 'KECAMATAN 2',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 1',
                'warna' => 'PUTIH',
                'hargajual' => 178914365,
                'discount' => 8396396,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020018',
                'tanggal' => '2025-02-21',
                'nama' => 'Customer 34',
                'nohp' => '82313323253',
                'alamat' => 'Jalan Raya 33',
                'kelurahan' => 'KELURAHAN 34',
                'kecamatan' => 'KECAMATAN 27',
                'kota' => 'KOTA 6',
                'tipe' => 'Mobil 1',
                'warna' => 'PUTIH',
                'hargajual' => 175696862,
                'discount' => 12000000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor' => 'UF25020030',
                'tanggal' => '2025-02-28',
                'nama' => 'Customer 17',
                'nohp' => '82313323254',
                'alamat' => 'Jalan Raya 34',
                'kelurahan' => 'KELURAHAN 17',
                'kecamatan' => 'KECAMATAN 13',
                'kota' => 'KOTA 3',
                'tipe' => 'Mobil 4',
                'warna' => 'PUTIH',
                'hargajual' => 161567229,
                'discount' => 12000000,
                'status' => 'Kredit',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('leads')->insert($leads);
    }
}
